### ISSUE TITLE
Waiting for SDK to start

### ISSUE THREAD

**Issue by Squidy06** [Heyzap/heyzap-cordova#12]
Hello, 
I am trying to use Heyzap into my Ionic App using your Cordova plugin.

Some details: 

- I completed your “Integration Wizard”: 
https://dl.dropboxusercontent.com/u/19864640/scr/1479481752.jpg

- Heyzap app config: 
https://dl.dropboxusercontent.com/u/19864640/scr/1479482031.jpg

- Javascript code used in app: 
http://pastebin.com/TYa0Rxvh

- I also put console.log into .start's Promise and it's called up

- I am trying to run the app into Emulator

Problem: app is being built without problems, but when I'm trying to show Mediation Debug View something like this shows up: 
https://dl.dropboxusercontent.com/u/19864640/scr/1479482200.jpg 
with following errors in console: 
http://pastebin.com/JnhfjBWB

What is the reason of such problem?

**Comment by vintage** [comment]
Hey @Squidy06 

I've had same issue. You have to fill out the payment details on the Heyzap. For more details check my original report - https://github.com/Heyzap/heyzap-cordova/issues/8

**Comment by Squidy06** [comment]
@vintage Thank you!

But why is this mandatory even for testing the app?

**Comment by vintage** [comment]
Good question, but I don't know the answer for it, sorry. Additionally if you would like to use banner ads, they do not work - https://github.com/Heyzap/heyzap-cordova/issues/9

If you just want to use interstitial & reward videos - you can play with the library. Otherwise I would go and look something different (eg. https://github.com/ratson/cordova-plugin-admob-free) for banner ads.
