### ISSUE TITLE
symbol(s) not found for architecture i386

### ISSUE THREAD

**Issue by rafaellop** [Heyzap/heyzap-cordova#32]
Building for release on iOS:

![image11](https://user-images.githubusercontent.com/8421184/32102713-d9b771c2-bb1d-11e7-9966-b34ea429bb28.png)

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_HZBannerAdOptions", referenced from:
      objc-class-ref in CDVHZBannerAd.o
  "_OBJC_CLASS_$_HZBannerAd", referenced from:
      objc-class-ref in CDVHZBannerAd.o
  "_OBJC_CLASS_$_HZShowOptions", referenced from:
      objc-class-ref in CDVHZIncentivizedAd.o
  "_OBJC_CLASS_$_HZInterstitialAd", referenced from:
      objc-class-ref in CDVHZInterstitialAd.o
  "_OBJC_CLASS_$_HZIncentivizedAd", referenced from:
      objc-class-ref in CDVHZIncentivizedAd.o
  "_OBJC_CLASS_$_HZVideoAd", referenced from:
      objc-class-ref in CDVHZVideoAd.o
  "_OBJC_CLASS_$_HeyzapAds", referenced from:
      objc-class-ref in CDVHeyzapAds.o
ld: symbol(s) not found for architecture i386

**Comment by ekilah** [comment]
https://developers.heyzap.com/docs/changelog

```
9.14.1 Released on October 4, 2017
iOS

Changes

Removed the i386 and armv7s architectures from the binary to reduce the file size. Now, the included architectures are: armv7, arm64, and x86_64 (simulator)
```

**Comment by ekilah** [comment]
You will need to use a newer simulator on the 64-bit architecture to use the newer version of the Heyzap SDK.

**Comment by rafaellop** [comment]
What do you mean as newer? I'm using xcode 8.1 + ios sim 10.3.1.

**Comment by ekilah** [comment]
Check to see if your project is still building for the `i386` architecture even though you aren't using it. The build settings listed here are relevant to this:

* Build Active Architecture Only
* Architectures
* Valid Architectures

I believe it also depends on which simulator device you use.

**Comment by rafaellop** [comment]
For "Architectures" I've got `$(ARCHS_STANDARD)` which are only `arm7`, `arm64` for all build modes.
For "Build Active Architecture Only" the `true` is only for `Debug` value.
For "Valid Architectures" I've got `arm64`, `armv7`, `armv7`s for all build modes.

It seems OK for me. No `i386` arch.

**Comment by ekilah** [comment]
Use a list like this: http://blakespot.com/ios_device_specifications_grid.html

Check what simulated device you are building for. If you simulate with the iPhone 8, for instance, this error shouldn't occur, as I use the same settings as you listed above. If you simulate with the iPhone 4, it will, since the iPhone 4 uses a 32-bit CPU. At least, that is my experience - I just tried this this morning to see if I could at least get the error on the iPhone 4 simualtor, and I can.

FWIW, `ARCHS_STANDARD` (and/or other settings) changes for simulator builds. Simulators either use `i386` or `x86_64`.
